-- ══════════════════════════════════════════════════════════════
--  SEED — 219 films
--  Exécuter APRÈS schema.sql et functions.sql
--  Les apostrophes dans les titres SQL s'échappent avec ''
-- ══════════════════════════════════════════════════════════════

insert into public.films (id, titre, annee, realisateur, genre, sousgenre, poster, saison) values
(1,  'Citizen Kane',                   1941,'Orson Welles',                 'Drame',     'Biopic',              'https://image.tmdb.org/t/p/w300/sav0jxhqiH0bPr2vZFU0Kjt2nZL.jpg',1),
(2,  'Le Parrain',                     1972,'Francis Ford Coppola',         'Crime',     'Drame familial',      'https://image.tmdb.org/t/p/w300/3bhkrj58Vtu7enYsLegHnDmni3.jpg', 1),
(3,  'Apocalypse Now',                 1979,'Francis Ford Coppola',         'Guerre',    'Drame épique',        'https://image.tmdb.org/t/p/w300/gQB8Y5RCMkv2zwzFHbUJX3kAhvA.jpg', 1),
(4,  'Taxi Driver',                    1976,'Martin Scorsese',              'Drame',     'Thriller',            'https://image.tmdb.org/t/p/w300/ekstpH614fwDX8DUln1a2Opz0N8.jpg', 1),
(5,  'Blade Runner',                   1982,'Ridley Scott',                 'SF',        'Film noir',           'https://image.tmdb.org/t/p/w300/63N9uy8nd9j7Eog2axPQ8lbr3Wj.jpg', 1),
(6,  'Gladiator',                      2000,'Ridley Scott',                 'Action',    'Historique',          'https://image.tmdb.org/t/p/w300/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg', 1),
(7,  'Parasite',                       2019,'Bong Joon-ho',                 'Drame',     'Thriller',            'https://image.tmdb.org/t/p/w300/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', 1),
(8,  'Forrest Gump',                   1994,'Robert Zemeckis',              'Drame',     'Comédie',             'https://image.tmdb.org/t/p/w300/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg', 1),
(9,  'Titanic',                        1997,'James Cameron',                'Drame',     'Romance',             'https://image.tmdb.org/t/p/w300/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg', 1),
(10, 'La Liste de Schindler',          1993,'Steven Spielberg',             'Drame',     'Historique',          'https://image.tmdb.org/t/p/w300/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg', 1),
(11, 'Les Évadés',                     1994,'Frank Darabont',               'Drame',     'Prison',              'https://image.tmdb.org/t/p/w300/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg', 1),
(12, 'Inception',                      2010,'Christopher Nolan',            'SF',        'Thriller',            'https://image.tmdb.org/t/p/w300/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg', 1),
(13, 'Interstellar',                   2014,'Christopher Nolan',            'SF',        'Aventure',            'https://image.tmdb.org/t/p/w300/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', 1),
(14, 'The Dark Knight',                2008,'Christopher Nolan',            'Action',    'Super-héros',         'https://image.tmdb.org/t/p/w300/qJ2tW6WMUDux911r6m7haRef0WH.jpg', 1),
(15, 'Mad Max: Fury Road',             2015,'George Miller',                'Action',    'SF',                  'https://image.tmdb.org/t/p/w300/8tZYtuWezp8JbcsvHfd1XkHSkgo.jpg', 1),
(16, 'Bernie',                         1996,'Albert Dupontel',              'Comédie',   'Noir',                'https://image.tmdb.org/t/p/w300/qxJMNiZnrNXLZ5p0MfFNSSSAMU.jpg',  1),
(17, 'Le Créateur',                    1999,'Albert Dupontel',              'Comédie',   'Absurde',             'https://image.tmdb.org/t/p/w300/bxQ5RQiCW2qrFJMQs3MSY1jS3jK.jpg', 1),
(18, 'Enfermés dehors',                2006,'Albert Dupontel',              'Comédie',   'Social',              'https://image.tmdb.org/t/p/w300/sMqXhMVvgbk7R3SFBh3RWaTBRkT.jpg', 1),
(19, 'Le Vilain',                      2009,'Albert Dupontel',              'Comédie',   'Noir',                'https://image.tmdb.org/t/p/w300/7TlFDNOnS3aaFdCBJBFr1SXFBG4.jpg', 1),
(20, '9 mois ferme',                   2013,'Albert Dupontel',              'Comédie',   'Judiciaire',          'https://image.tmdb.org/t/p/w300/m4DLObNNa3TnMmEfVBwS9D7fMl8.jpg', 1),
(21, 'Au revoir là-haut',              2017,'Albert Dupontel',              'Drame',     'Historique',          'https://image.tmdb.org/t/p/w300/vLfRHpnbC8yPfNkL5fhS1JJG8wS.jpg', 1),
(22, 'Adieu les cons',                 2020,'Albert Dupontel',              'Comédie',   'Poétique',            'https://image.tmdb.org/t/p/w300/qiWp6s5V9A3e1YJPiVvdHCZFYBz.jpg', 1),
(23, 'Second tour',                    2023,'Albert Dupontel',              'Comédie',   'Satirique',           'https://image.tmdb.org/t/p/w300/aW4vQRRMi1JjI4VwFKAjk2Tp9BQ.jpg', 1),
(24, 'Rashōmon',                       1950,'Akira Kurosawa',               'Drame',     'Policier',            'https://image.tmdb.org/t/p/w300/dKlFicDIJOkyIB4JBdMV0KJMl0t.jpg', 1),
(25, 'Les 400 coups',                  1959,'François Truffaut',            'Drame',     'Nouvelle Vague',      'https://image.tmdb.org/t/p/w300/1o5p0cJVtWqnHW5Rj1WMXN6FDCS.jpg', 1),
(26, 'À bout de souffle',              1960,'Jean-Luc Godard',              'Drame',     'Nouvelle Vague',      'https://image.tmdb.org/t/p/w300/rLHv7d5GgMgrFhpCziBwLVyPMJD.jpg', 1),
(27, 'Cléo de 5 à 7',                 1962,'Agnès Varda',                  'Drame',     'Nouvelle Vague',      'https://image.tmdb.org/t/p/w300/7m7GijAlRJoG0l9CJJW1eDlNYJY.jpg', 1),
(28, 'L''Enfance d''Ivan',             1962,'Andreï Tarkovski',             'Guerre',    'Drame',               'https://image.tmdb.org/t/p/w300/xAQSoOBfp2mXqDoWRdOFkRLVSWJ.jpg', 1),
(29, '2001 : L''Odyssée de l''espace', 1968,'Stanley Kubrick',              'SF',        'Philosophique',       'https://image.tmdb.org/t/p/w300/ve72VxNqsuTFBBM9Z3kbCqXlrGT.jpg', 1),
(30, 'Orange mécanique',               1971,'Stanley Kubrick',              'SF',        'Dystopie',            'https://image.tmdb.org/t/p/w300/4fHResvlYMqeQ2Nbo3MKFMF8Nvf.jpg', 1),
(31, 'Le Parrain II',                  1974,'Francis Ford Coppola',         'Crime',     'Drame épique',        'https://image.tmdb.org/t/p/w300/bVq65huQ8vHDd1a4Z37QtuyEvSw.jpg',  1),
(32, 'Solaris',                        1972,'Andreï Tarkovski',             'SF',        'Drame psychologique', 'https://image.tmdb.org/t/p/w300/gPBNWtknHzfO6g7bKCYuJw4SaK5.jpg',  1),
(33, 'Chinatown',                      1974,'Roman Polanski',               'Policier',  'Film noir',           'https://image.tmdb.org/t/p/w300/barAkuEAzQGGzBHYaEzjlxhQR80.jpg',  1),
(34, 'Les Dents de la mer',            1975,'Steven Spielberg',             'Thriller',  'Horreur',             'https://image.tmdb.org/t/p/w300/lxM6e856i1oAGXiODWujIBKhO0U.jpg',  1),
(35, 'Rocky',                          1976,'John G. Avildsen',             'Drame',     'Sport',               'https://image.tmdb.org/t/p/w300/sHuDHFBjbJfSRjnjxzajQmBpxsv.jpg',  1),
(36, 'E.T.',                           1982,'Steven Spielberg',             'SF',        'Aventure',            'https://image.tmdb.org/t/p/w300/an0nD6uq6byfxXCfk6lQBzdL2J1.jpg',  1),
(37, 'Scarface',                       1983,'Brian De Palma',               'Crime',     'Drame',               'https://image.tmdb.org/t/p/w300/iQ5ztdjvteGeboxtmRdXEChJOHh.jpg',  1),
(38, 'Amadeus',                        1984,'Miloš Forman',                 'Drame',     'Biopic',              'https://image.tmdb.org/t/p/w300/8PUZFNaWGDFAbpnrCQ7GnO9GALL.jpg',  1),
(39, 'Top Gun',                        1986,'Tony Scott',                   'Action',    'Drame',               'https://image.tmdb.org/t/p/w300/xUuHj3CgmZQ9P2cMaqQs3oxpPco.jpg',  1),
(40, 'Platoon',                        1986,'Oliver Stone',                 'Guerre',    'Drame',               'https://image.tmdb.org/t/p/w300/4fct4bkAlWeTMisMzF6Vh7HGxDY.jpg',  1),
(41, 'Full Metal Jacket',              1987,'Stanley Kubrick',              'Guerre',    'Drame',               'https://image.tmdb.org/t/p/w300/n98mCFHV9e92AgAXaMImEY0wOSb.jpg',  1),
(42, 'Piège de cristal',               1988,'John McTiernan',               'Action',    'Thriller',            'https://image.tmdb.org/t/p/w300/yFihWxQcmqcaBR31QM6Y8gT6aYV.jpg',  1),
(43, 'Le Cercle des poètes disparus',  1989,'Peter Weir',                   'Drame',     'Coming-of-age',       'https://image.tmdb.org/t/p/w300/e0Ew7b4WnqSSbHAfAKOhITMBRHa.jpg',  1),
(44, 'Goodfellas',                     1990,'Martin Scorsese',              'Crime',     'Biopic',              'https://image.tmdb.org/t/p/w300/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',  1),
(45, 'Pretty Woman',                   1990,'Garry Marshall',               'Comédie',   'Romance',             'https://image.tmdb.org/t/p/w300/vgpHFJB3LRuEHGVMpyMCFUXhPQ5.jpg',  1),
(46, 'Terminator',                     1984,'James Cameron',                'SF',        'Action',              'https://image.tmdb.org/t/p/w300/9vu2ms7lo8oMnMmHpMoHfexmaMB.jpg',  1),
(47, 'Le Silence des agneaux',         1991,'Jonathan Demme',               'Thriller',  'Horreur',             'https://image.tmdb.org/t/p/w300/rplLJ2hPcOQmkFhTqUte0MkosOB.jpg',  1),
(48, 'Reservoir Dogs',                 1992,'Quentin Tarantino',            'Crime',     'Thriller',            'https://image.tmdb.org/t/p/w300/vFsoT3FlxLPdNSPbHJCM2SBzRBZ.jpg',  1),
(49, 'Impitoyable',                    1992,'Clint Eastwood',               'Western',   'Drame',               'https://image.tmdb.org/t/p/w300/6bz12YNu5dZHalXo0cJdRflOv6H.jpg',  1),
(50, 'Le Seigneur des anneaux',        2001,'Peter Jackson',                'Fantaisie', 'Aventure',            'https://image.tmdb.org/t/p/w300/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',  1),
(51, 'Pulp Fiction',                   1994,'Quentin Tarantino',            'Crime',     'Thriller',            'https://image.tmdb.org/t/p/w300/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',  1),
(52, 'Seven',                          1995,'David Fincher',                'Thriller',  'Policier',            'https://image.tmdb.org/t/p/w300/6yoghtyTpznpBik8EngEmJskVnS.jpg',  1),
(53, 'Heat',                           1995,'Michael Mann',                 'Crime',     'Thriller',            'https://image.tmdb.org/t/p/w300/um1AlRXjNqK0AP1MnfmJZJvWMoH.jpg',  1),
(54, 'Braveheart',                     1995,'Mel Gibson',                   'Action',    'Historique',          'https://image.tmdb.org/t/p/w300/or1gBugydmjToAEq7OZY0owwFk.jpg',   1),
(55, 'Toy Story',                      1995,'John Lasseter',                'Animation', 'Aventure',            'https://image.tmdb.org/t/p/w300/uXDfjJbdP4ijW5hWSBrPu9LDt56.jpg',  1),
(56, 'Fargo',                          1996,'Joel & Ethan Coen',            'Crime',     'Comédie noire',       'https://image.tmdb.org/t/p/w300/pFwox6zeHkiG8pnmlbfhQlc0PuO.jpg',  1),
(57, 'Trainspotting',                  1996,'Danny Boyle',                  'Drame',     'Addiction',           'https://image.tmdb.org/t/p/w300/9KOHKRpBmFCwCJiJGLAzw4oAKX2.jpg',  1),
(58, 'Princesse Mononoké',             1997,'Hayao Miyazaki',               'Animation', 'Fantaisie',           'https://image.tmdb.org/t/p/w300/jHArlo9BmPWhOHHILaGDPEhXVkd.jpg',  1),
(59, 'The Big Lebowski',               1998,'Joel & Ethan Coen',            'Comédie',   'Crime',               'https://image.tmdb.org/t/p/w300/beV4jzFcPFQAHNTCx0Q6qMGXSXz.jpg',  1),
(60, 'Il faut sauver le soldat Ryan',  1998,'Steven Spielberg',             'Guerre',    'Drame',               'https://image.tmdb.org/t/p/w300/uqx572gCWQ81u2q7isVpbJGHCuN.jpg',  1),
(61, 'Matrix',                         1999,'Wachowski',                    'SF',        'Action',              'https://image.tmdb.org/t/p/w300/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',  1),
(62, 'Fight Club',                     1999,'David Fincher',                'Drame',     'Thriller',            'https://image.tmdb.org/t/p/w300/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',  1),
(63, 'American Beauty',                1999,'Sam Mendes',                   'Drame',     'Comédie noire',       'https://image.tmdb.org/t/p/w300/wby9315QzAjPlME6XECgIU4Y8D1.jpg',  1),
(64, 'Memento',                        2000,'Christopher Nolan',            'Thriller',  'Psychologique',       'https://image.tmdb.org/t/p/w300/yuNs09hvpHVU1cBTCAk9zxsL2oW.jpg',  1),
(65, 'Requiem for a Dream',            2000,'Darren Aronofsky',             'Drame',     'Addiction',           'https://image.tmdb.org/t/p/w300/nOd6vjEmzCT0k4VYqsA2hwyi87C.jpg',  1),
(66, 'Amélie',                         2001,'Jean-Pierre Jeunet',           'Comédie',   'Romance',             'https://image.tmdb.org/t/p/w300/x5xtFoTlQ7QbMmMaMb3ARxUMvxM.jpg',  1),
(67, 'La Cité de Dieu',               2002,'Fernando Meirelles',           'Crime',     'Drame social',        'https://image.tmdb.org/t/p/w300/k7eYdWvhYQyRQoU2TB2A2Xu2grZ.jpg',  1),
(68, 'Catch Me If You Can',            2002,'Steven Spielberg',             'Crime',     'Biopic',              'https://image.tmdb.org/t/p/w300/hXWBc0ioZE4JMOAQbsuGgBEe7Kc.jpg',  1),
(69, 'Kill Bill',                      2003,'Quentin Tarantino',            'Action',    'Revenge',             'https://image.tmdb.org/t/p/w300/v7TaX8kXMXs5yFFGR41guUDNcnB.jpg',  1),
(70, 'Oldboy',                         2003,'Park Chan-wook',               'Thriller',  'Mystère',             'https://image.tmdb.org/t/p/w300/pWDtjs568ZfOTMbURQBmHx4LATH.jpg',  1),
(71, 'Eternal Sunshine of the Spotless Mind',2004,'Michel Gondry',         'Drame',     'Romance',             'https://image.tmdb.org/t/p/w300/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg',  1),
(72, 'Million Dollar Baby',            2004,'Clint Eastwood',               'Drame',     'Sport',               'https://image.tmdb.org/t/p/w300/b3VuZgPzS3ZzNWoNJTEE1fJe0Vl.jpg',  1),
(73, 'Batman Begins',                  2005,'Christopher Nolan',            'Action',    'Super-héros',         'https://image.tmdb.org/t/p/w300/dr6C9GpvNaPKAGBuiqSq5p6nSDc.jpg',  1),
(74, 'Brokeback Mountain',             2005,'Ang Lee',                      'Drame',     'Romance',             'https://image.tmdb.org/t/p/w300/o1nRzEBYGrKFpYQToxNrfUf3fQD.jpg',  1),
(75, 'Le Prestige',                    2006,'Christopher Nolan',            'Thriller',  'Mystère',             'https://image.tmdb.org/t/p/w300/5MXyQfz8xUP3dIFPTubhTsbFY6K.jpg',  1),
(76, 'Casino Royale',                  2006,'Martin Campbell',              'Action',    'Espionnage',          'https://image.tmdb.org/t/p/w300/34m2tygAYBGqA9MXKhRDtzYd4Eg.jpg',  1),
(77, 'Les Infiltrés',                  2006,'Martin Scorsese',              'Crime',     'Thriller',            'https://image.tmdb.org/t/p/w300/kSCHXTB9bBQhXTalDLqJE6YTnnr.jpg',  1),
(78, 'There Will Be Blood',            2007,'Paul Thomas Anderson',         'Drame',     'Historique',          'https://image.tmdb.org/t/p/w300/fa0RDkAlCec0STeMNAhPaF89q6U.jpg',  1),
(79, 'No Country for Old Men',         2007,'Joel & Ethan Coen',            'Crime',     'Western',             'https://image.tmdb.org/t/p/w300/6OEBp0Gqv6DsOgi8diPUslT2kbA.jpg',  1),
(80, 'Into the Wild',                  2007,'Sean Penn',                    'Drame',     'Aventure',            'https://image.tmdb.org/t/p/w300/qLEzpDRpXpjGf0pNuXkF6s5bYXl.jpg',  1),
(81, 'Gran Torino',                    2008,'Clint Eastwood',               'Drame',     'Drame social',        'https://image.tmdb.org/t/p/w300/nLTlKqBNkWamUMN7TA0AAnBJtlv.jpg',  1),
(82, 'Django Unchained',               2012,'Quentin Tarantino',            'Western',   'Action',              'https://image.tmdb.org/t/p/w300/5WJlxuuBGtlQjPFYRLTZmQFqTbA.jpg',  1),
(83, 'Incendies',                      2010,'Denis Villeneuve',             'Drame',     'Guerre',              'https://image.tmdb.org/t/p/w300/lGhGTRYGAhWsq38fcpqhFoAoiGV.jpg',  1),
(84, 'Intouchables',                   2011,'Nakache & Toledano',           'Comédie',   'Drame',               'https://image.tmdb.org/t/p/w300/6fmZuJRBNmMJWrIbqCbEWaGg2gZ.jpg',  1),
(85, 'Prisoners',                      2013,'Denis Villeneuve',             'Thriller',  'Crime',               'https://image.tmdb.org/t/p/w300/lbpFEMuPBsAOiMKuKrirqpEyNYs.jpg',  1),
(86, 'Blade Runner 2049',              2017,'Denis Villeneuve',             'SF',        'Film noir',           'https://image.tmdb.org/t/p/w300/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',  1),
(87, 'Tu ne tueras point',             2016,'Mel Gibson',                   'Guerre',    'Biopic',              'https://image.tmdb.org/t/p/w300/j9O2FBdVf5sPf7WlWDxPv5rPOFQ.jpg',  1),
(88, 'Gone Girl',                      2014,'David Fincher',                'Thriller',  'Drame',               'https://image.tmdb.org/t/p/w300/bth7GcMnZvwBqzCRFM46VFQ9Yd5.jpg',  1),
(89, 'Spotlight',                      2015,'Tom McCarthy',                 'Drame',     'Policier',            'https://image.tmdb.org/t/p/w300/fJRU9fRsITQQlwfbz1V3vZqIXnl.jpg',  1),
(90, 'La La Land',                     2016,'Damien Chazelle',              'Comédie',   'Musical',             'https://image.tmdb.org/t/p/w300/uDO8zWDhfWwoFdKS4fzkUJt0Bs0.jpg',  1),
(93, '1917',                           2019,'Sam Mendes',                   'Guerre',    'Thriller',            'https://image.tmdb.org/t/p/w300/iZf0KyrE25z1sage4SYiFOd4L7W.jpg',  1),
(94, 'The Father',                     2020,'Florian Zeller',               'Drame',     'Psychologique',       'https://image.tmdb.org/t/p/w300/kgwjIb2JDHRhNk13lmSxiClFjVk.jpg',  1),
(95, 'Dune',                           2021,'Denis Villeneuve',             'SF',        'Aventure',            'https://image.tmdb.org/t/p/w300/d5NXSklpcvkCgnEF8VIkZKUhpPg.jpg',  1),
(96, 'Oppenheimer',                    2023,'Christopher Nolan',            'Drame',     'Biopic',              'https://image.tmdb.org/t/p/w300/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',  1),
(100,'Chainsaw Man – The Reze Arc',    2024,'MAPPA',                        'Animation', 'Action',              'https://image.tmdb.org/t/p/w300/5gqGjlUhKPfTyFqhbJwBf97xmPf.jpg',  1),
(101,'Aliens',                         1986,'James Cameron',                'SF',        'Horreur',             'https://image.tmdb.org/t/p/w300/r9oQROgCZOVFHYECyFB3q73pDDd.jpg',  1),
(102,'The Thing',                      1982,'John Carpenter',               'Horreur',   'SF',                  'https://image.tmdb.org/t/p/w300/tzGY51oI858LJRSys4KAm57un3z.jpg',  1),
(103,'Zodiac',                         2007,'David Fincher',                'Policier',  'Thriller',            'https://image.tmdb.org/t/p/w300/qPYLkuJlgaAVEEsfBjwV7OeVTqs.jpg',  1),
(104,'The Social Network',             2010,'David Fincher',                'Drame',     'Biopic',              'https://image.tmdb.org/t/p/w300/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg',  1),
(105,'Whiplash',                       2014,'Damien Chazelle',              'Drame',     'Musique',             'https://image.tmdb.org/t/p/w300/7fn624j5lj3xTme2SgiLCeuedmO.jpg',  1),
(106,'Black Swan',                     2010,'Darren Aronofsky',             'Thriller',  'Psychologique',       'https://image.tmdb.org/t/p/w300/vxJFF5MbWwWdFGBSGXYEAi3ojBU.jpg',  1),
(107,'The Revenant',                   2015,'Alejandro G. Iñárritu',        'Aventure',  'Survie',              'https://image.tmdb.org/t/p/w300/ji3ecJphATlVgWNY0B0RVXZizR2.jpg',  1),
(108,'Birdman',                        2014,'Alejandro G. Iñárritu',        'Comédie',   'Drame',               'https://image.tmdb.org/t/p/w300/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',  1),
(109,'Her',                            2013,'Spike Jonze',                  'SF',        'Romance',             'https://image.tmdb.org/t/p/w300/eCOtqtfvn7mxGGGuOFzuqFQFyDd.jpg',  1),
(110,'Arrival',                        2016,'Denis Villeneuve',             'SF',        'Drame',               'https://image.tmdb.org/t/p/w300/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg',  1),
(111,'Sicario',                        2015,'Denis Villeneuve',             'Crime',     'Thriller',            'https://image.tmdb.org/t/p/w300/jMu8SLqA3OBgdxaxKPEKS1apQpL.jpg',  1),
(112,'Enemy',                          2013,'Denis Villeneuve',             'Thriller',  'Mystère',             'https://image.tmdb.org/t/p/w300/cfQNIfHaHLSH7fqvLMFbsNtCPeG.jpg',  1),
(113,'Nightcrawler',                   2014,'Dan Gilroy',                   'Thriller',  'Crime',               'https://image.tmdb.org/t/p/w300/vEMoVbqv73A9V6ik3fWvkCx9wv9.jpg',  1),
(114,'Donnie Darko',                   2001,'Richard Kelly',                'SF',        'Thriller',            'https://image.tmdb.org/t/p/w300/cv2bx6UjFJlGOhMBX0BdTMbXhp.jpg',  1),
(115,'The Truman Show',                1998,'Peter Weir',                   'Drame',     'Comédie',             'https://image.tmdb.org/t/p/w300/vuza0WqY239yBXOadKlGwJsZJFE.jpg',  1),
(116,'The Wolf of Wall Street',        2013,'Martin Scorsese',              'Crime',     'Biopic',              'https://image.tmdb.org/t/p/w300/vDHsLnOWKlPGmVf9pxD3cdoyTnT.jpg',  1),
(118,'Shrek',                          2001,'Andrew Adamson',               'Animation', 'Comédie',             'https://image.tmdb.org/t/p/w300/iB64vpL3dIObOtMZgX3RqdVdQDc.jpg',  1),
(119,'Ratatouille',                    2007,'Brad Bird',                    'Animation', 'Comédie',             'https://image.tmdb.org/t/p/w300/npHNjldbeTHdKKGra3L68ojpjFh.jpg',  1),
(120,'Wall-E',                         2008,'Andrew Stanton',               'Animation', 'SF',                  'https://image.tmdb.org/t/p/w300/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg',  1),
(121,'Up',                             2009,'Pete Docter',                  'Animation', 'Aventure',            'https://image.tmdb.org/t/p/w300/paCpnfMT5ELuXLZYSFWABo7KDOA.jpg',  1),
(122,'Coco',                           2017,'Lee Unkrich',                  'Animation', 'Aventure',            'https://image.tmdb.org/t/p/w300/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg',  1),
(123,'Le Roi Lion',                    1994,'Roger Allers',                 'Animation', 'Aventure',            'https://image.tmdb.org/t/p/w300/sKCr8WHbnp9f3H4rsOLngHpalNx.jpg',  1),
(124,'Le Voyage de Chihiro',           2001,'Hayao Miyazaki',               'Animation', 'Fantaisie',           'https://image.tmdb.org/t/p/w300/d3izgkS8Qj6AH3k2GKGV5D53G2K.jpg',  1),
(125,'Your Name',                      2016,'Makoto Shinkai',               'Animation', 'Romance',             'https://image.tmdb.org/t/p/w300/q719jXXEzOoYaps6babgKnONONX.jpg',  1),
(126,'Akira',                          1988,'Katsuhiro Otomo',              'Animation', 'SF',                  'https://image.tmdb.org/t/p/w300/neZ0ykEsPqxamsX6o5QNnFAFiGB.jpg',  1),
(127,'Ghost in the Shell',             1995,'Mamoru Oshii',                 'Animation', 'SF',                  'https://image.tmdb.org/t/p/w300/kqnBLLZenHqHiCM1yRJIaWsZWYM.jpg',  1),
(128,'Perfect Blue',                   1997,'Satoshi Kon',                  'Animation', 'Thriller',            'https://image.tmdb.org/t/p/w300/79LMoCWzqeEoMHqtNBL2GidLqJk.jpg',  1),
(129,'The Grand Budapest Hotel',       2014,'Wes Anderson',                 'Comédie',   'Aventure',            'https://image.tmdb.org/t/p/w300/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg',  1),
(130,'Moonrise Kingdom',               2012,'Wes Anderson',                 'Comédie',   'Romance',             'https://image.tmdb.org/t/p/w300/jtPDOybZNkDn0HWPqxBrVsHy2JJ.jpg',  1),
(131,'Fantastic Mr. Fox',              2009,'Wes Anderson',                 'Animation', 'Comédie',             'https://image.tmdb.org/t/p/w300/GQ4QHGEIGsEzO2HgFhiOBiqtWg.jpg',   1),
(132,'The Lighthouse',                 2019,'Robert Eggers',                'Horreur',   'Drame',               'https://image.tmdb.org/t/p/w300/3dEjDMnXnBhCNiQh5ngIzpE7SnV.jpg',  1),
(133,'The Witch',                      2015,'Robert Eggers',                'Horreur',   'Période',             'https://image.tmdb.org/t/p/w300/fvvONjBKT1XKRK6U3Ksa1fFkx7V.jpg',  1),
(134,'Midsommar',                      2019,'Ari Aster',                    'Horreur',   'Drame',               'https://image.tmdb.org/t/p/w300/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg',  1),
(135,'Get Out',                        2017,'Jordan Peele',                 'Horreur',   'Thriller',            'https://image.tmdb.org/t/p/w300/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg',  1),
(136,'Us',                             2019,'Jordan Peele',                 'Horreur',   'Thriller',            'https://image.tmdb.org/t/p/w300/ux2maQFe2CSYMdIEoFSp94mMFfq.jpg',  1),
(137,'Nope',                           2022,'Jordan Peele',                 'Horreur',   'SF',                  'https://image.tmdb.org/t/p/w300/AcKVlWaNVVVFQwynSr1MpALaz0n.jpg',  1),
(138,'The Batman',                     2022,'Matt Reeves',                  'Action',    'Super-héros',         'https://image.tmdb.org/t/p/w300/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg',  1),
(139,'Avengers: Endgame',              2019,'Russo Brothers',               'Action',    'Super-héros',         'https://image.tmdb.org/t/p/w300/or06FN3Dka5tukK1e9sl16pB3iy.jpg',  1),
(140,'Spider-Man: No Way Home',        2021,'Jon Watts',                    'Action',    'Super-héros',         'https://image.tmdb.org/t/p/w300/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',  1),
(141,'Harry Potter à l''école des sorciers',2001,'Chris Columbus',          'Fantaisie', 'Aventure',            'https://image.tmdb.org/t/p/w300/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg',  1),
(142,'Pirates des Caraïbes',           2003,'Gore Verbinski',               'Action',    'Aventure',            'https://image.tmdb.org/t/p/w300/vx1u0uwxpwSLnMOOJqHb98i1tBa.jpg',  1),
(144,'Mission: Impossible',            1996,'Brian De Palma',               'Action',    'Espionnage',          'https://image.tmdb.org/t/p/w300/LCkiJfbJfkEnhb99UPIYXGBu1T.jpg',   1),
(145,'Skyfall',                        2012,'Sam Mendes',                   'Action',    'Espionnage',          'https://image.tmdb.org/t/p/w300/y5uoqCJqgKHHcFBFRLpLPAMkL6T.jpg',  1),
(146,'Tenet',                          2020,'Christopher Nolan',            'SF',        'Action',              'https://image.tmdb.org/t/p/w300/k68nPLbIST6NP96JmTxmZijZcpx.jpg',  1),
(147,'Dunkerque',                      2017,'Christopher Nolan',            'Guerre',    'Thriller',            'https://image.tmdb.org/t/p/w300/x6NpvdCBgwbBQpGikFy7RzHiEfA.jpg',  1),
(148,'The Irishman',                   2019,'Martin Scorsese',              'Crime',     'Biopic',              'https://image.tmdb.org/t/p/w300/or06FN3Dka5tukK1e9sl16pB3iy.jpg',  1),
(149,'Killers of the Flower Moon',     2023,'Martin Scorsese',              'Crime',     'Historique',          'https://image.tmdb.org/t/p/w300/dB6aHCMBVTDTe7JNnxuHMnVfFgL.jpg',  1),
(150,'Casino',                         1995,'Martin Scorsese',              'Crime',     'Biopic',              'https://image.tmdb.org/t/p/w300/9l1pACCIpVStKFMN6zqxcGJnqGM.jpg',  1),
(151,'The Hateful Eight',              2015,'Quentin Tarantino',            'Western',   'Thriller',            'https://image.tmdb.org/t/p/w300/tQiSzFlVuXaGPD3Ws1vOZYKpXGM.jpg',  1),
(152,'Once Upon a Time in Hollywood',  2019,'Quentin Tarantino',            'Drame',     'Comédie',             'https://image.tmdb.org/t/p/w300/8j58iEBw9pOXFD2L0nt0ZXeHviB.jpg',  1),
(153,'Inglourious Basterds',           2009,'Quentin Tarantino',            'Guerre',    'Thriller',            'https://image.tmdb.org/t/p/w300/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg',  1),
(154,'The Pianist',                    2002,'Roman Polanski',               'Drame',     'Guerre',              'https://image.tmdb.org/t/p/w300/2hFvxCCWrTmCYwfy7yum0GKSmly.jpg',  1),
(155,'La vie est belle',               1997,'Roberto Benigni',              'Drame',     'Comédie',             'https://image.tmdb.org/t/p/w300/mfloJCPjulGJqfp7uGpd3vbVEzC.jpg',  1),
(156,'Roma',                           2018,'Alfonso Cuarón',               'Drame',     'Autobiographique',    'https://image.tmdb.org/t/p/w300/dtLNiMAN2DpMUfBMiNjGm4eN50H.jpg',  1),
(157,'Marriage Story',                 2019,'Noah Baumbach',                'Drame',     'Romance',             'https://image.tmdb.org/t/p/w300/pZekG6xabFRRKEOBqQOGMsF1npe.jpg',  1),
(158,'Manchester by the Sea',          2016,'Kenneth Lonergan',             'Drame',     'Familial',            'https://image.tmdb.org/t/p/w300/6oOAA4B6J8WfVRVMjHm5VgW5Pdr.jpg',  1),
(159,'Sound of Metal',                 2019,'Darius Marder',                'Drame',     'Musique',             'https://image.tmdb.org/t/p/w300/9nHKmovOhSx4ATNv7YeOvSTb9WI.jpg',  1),
(160,'Everything Everywhere All at Once',2022,'Daniel Kwan & D. Scheinert','SF',        'Action',              'https://image.tmdb.org/t/p/w300/rKvCys0fMIIi1X9rmJBxTPLAtoU.jpg',  1),
(161,'Dune: Part Two',                 2024,'Denis Villeneuve',             'SF',        'Aventure',            'https://image.tmdb.org/t/p/w300/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg',  1),
(162,'Furiosa',                        2024,'George Miller',                'Action',    'SF',                  'https://image.tmdb.org/t/p/w300/iADOJ8Zymht2JPMoy3R7xceZpRC.jpg',  1),
(163,'Civil War',                      2024,'Alex Garland',                 'Thriller',  'Guerre',              'https://image.tmdb.org/t/p/w300/fc9NzVsGa6eDMfW4Gqwj2oF4NXZ.jpg',  1),
(164,'The Substance',                  2024,'Coralie Fargeat',              'Horreur',   'Corps',               'https://image.tmdb.org/t/p/w300/lqoMzCcZYEFK729d6qzt349fB4o.jpg',  1),
(165,'Nosferatu',                      2024,'Robert Eggers',                'Horreur',   'Période',             'https://image.tmdb.org/t/p/w300/5qGIxdEO841C0tdY8vOdLoRVrr0.jpg',  1),
(166,'Mickey 17',                      2025,'Bong Joon-ho',                 'SF',        'Comédie',             'https://image.tmdb.org/t/p/w300/7GpxDfKnm6qyCCTiNPgqGHxDFHK.jpg',  1),
(167,'Gladiator II',                   2024,'Ridley Scott',                 'Action',    'Historique',          'https://image.tmdb.org/t/p/w300/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg',  1),
(168,'Joker: Folie à Deux',            2024,'Todd Phillips',                'Drame',     'Musical',             'https://image.tmdb.org/t/p/w300/bIXHiqiHfFNFuzMFHLePohsAi3e.jpg',  1),
(169,'Deadpool & Wolverine',           2024,'Shawn Levy',                   'Action',    'Super-héros',         'https://image.tmdb.org/t/p/w300/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',  1),
(170,'Vice Versa 2',                   2024,'Kelsey Mann',                  'Animation', 'Comédie',             'https://image.tmdb.org/t/p/w300/vzmL6fP7ZIGCgUE6ELNnkubeijA.jpg',  1),
(171,'Le Mépris',                      1963,'Jean-Luc Godard',              'Drame',     'Drame de couple',     'https://image.tmdb.org/t/p/w300/4VGLAU5sGqiVHmWTRlIUByaA4yj.jpg',  1),
(172,'Paris, Texas',                   1984,'Wim Wenders',                  'Drame',     'Road movie',          'https://image.tmdb.org/t/p/w300/gXBIKP5YHDPGvY1LTYolYWiMRFO.jpg',  1),
(173,'Stalker',                        1979,'Andreï Tarkovski',             'SF',        'Philosophique',       'https://image.tmdb.org/t/p/w300/gCJzO1EBH1FRVdiSGJE35UThRPl.jpg',  1),
(174,'Andreï Roublev',                 1966,'Andreï Tarkovski',             'Drame',     'Historique',          'https://image.tmdb.org/t/p/w300/mQFGt0P5Qb5u3BZW1eFMjAJzMEL.jpg',  1),
(175,'Mulholland Drive',               2001,'David Lynch',                  'Thriller',  'Mystère',             'https://image.tmdb.org/t/p/w300/dK8LdHdGz8wRFi5LkSzQaPhkfkE.jpg',  1),
(176,'Lost Highway',                   1997,'David Lynch',                  'Thriller',  'Mystère',             'https://image.tmdb.org/t/p/w300/lcLCSl4L8dOxYRvQFdVOJl1PXSH.jpg',  1),
(177,'The Elephant Man',               1980,'David Lynch',                  'Drame',     'Biopic',              'https://image.tmdb.org/t/p/w300/iP5HEMcEXRoYlQ4M2mlFGl6S4Hy.jpg',  1),
(178,'The Tree of Life',               2011,'Terrence Malick',              'Drame',     'Philosophique',       'https://image.tmdb.org/t/p/w300/lIv1QieFA0vqfiav86axl1XNDZy.jpg',  1),
(179,'The Thin Red Line',              1998,'Terrence Malick',              'Guerre',    'Philosophique',       'https://image.tmdb.org/t/p/w300/pBJQk1MjKMaANmFQ56YJFwKkxMX.jpg',  1),
(180,'A Ghost Story',                  2017,'David Lowery',                 'Drame',     'Fantastique',         'https://image.tmdb.org/t/p/w300/t1a7jFzKlBNpIaStLqlnBhYf8Fn.jpg',  1),
(181,'First Reformed',                 2017,'Paul Schrader',                'Drame',     'Religieux',           'https://image.tmdb.org/t/p/w300/bqKjWgGRb3UjYMHSRJlEGpFCNeN.jpg',  1),
(182,'Uncut Gems',                     2019,'Josh & Benny Safdie',          'Thriller',  'Crime',               'https://image.tmdb.org/t/p/w300/g87oZhFHSGSFr9WAaQIMzWNekUI.jpg',  1),
(183,'Good Time',                      2017,'Josh & Benny Safdie',          'Crime',     'Thriller',            'https://image.tmdb.org/t/p/w300/gPwJnFpqiEKnFAKJCVqFDHM9uHt.jpg',  1),
(184,'The Florida Project',            2017,'Sean Baker',                   'Drame',     'Social',              'https://image.tmdb.org/t/p/w300/LpSCrNwFbV1vy5eMBF0bLWlH3nf.jpg',  1),
(185,'Moonlight',                      2016,'Barry Jenkins',                'Drame',     'Coming-of-age',       'https://image.tmdb.org/t/p/w300/qAwFbszVk7wDtE0UTHB0ZxQqMUv.jpg',  1),
(186,'12 Years a Slave',               2013,'Steve McQueen',                'Drame',     'Historique',          'https://image.tmdb.org/t/p/w300/xdANQHTFRvDqbGAkPiWMnpABM4O.jpg',  1),
(187,'Green Book',                     2018,'Peter Farrelly',               'Drame',     'Comédie',             'https://image.tmdb.org/t/p/w300/7BsvSuDQuoqhWmU2fL7W2GOcZHU.jpg',  1),
(188,'The Shape of Water',             2017,'Guillermo del Toro',           'Fantaisie', 'Romance',             'https://image.tmdb.org/t/p/w300/uu56o04gWr9tLNfWUy0WK01wJuX.jpg',  1),
(189,'Children of Men',                2006,'Alfonso Cuarón',               'SF',        'Thriller',            'https://image.tmdb.org/t/p/w300/kgOWzv0DYOEn2OJvjXhfKvQVFuI.jpg',  1),
(190,'Gravity',                        2013,'Alfonso Cuarón',               'SF',        'Thriller',            'https://image.tmdb.org/t/p/w300/6nGzGBmNfCPB5e5sj6RRYKXzRH.jpg',   1),
(191,'Le Labyrinthe de Pan',           2006,'Guillermo del Toro',           'Fantaisie', 'Guerre',              'https://image.tmdb.org/t/p/w300/htRZAnFsFdRGJhbzFfNbPmFMJRH.jpg',  1),
(192,'Hell or High Water',             2016,'David Mackenzie',              'Western',   'Crime',               'https://image.tmdb.org/t/p/w300/ygHsJDCBoatpLuScNZfSqWFCXUt.jpg',  1),
(193,'Wind River',                     2017,'Taylor Sheridan',              'Thriller',  'Policier',            'https://image.tmdb.org/t/p/w300/qb7YaHAcSIqHRqMzQOJAnkijMV5.jpg',  1),
(194,'The Big Short',                  2015,'Adam McKay',                   'Drame',     'Comédie',             'https://image.tmdb.org/t/p/w300/bWkfBzOBuHPRWOBpfw2Zn9HrwFk.jpg',  1),
(195,'Moneyball',                      2011,'Bennett Miller',               'Drame',     'Sport',               'https://image.tmdb.org/t/p/w300/3oAa8mJJ97CH9AeGEY6vjAxqcvZ.jpg',  1),
(196,'Ford v Ferrari',                 2019,'James Mangold',                'Drame',     'Sport',               'https://image.tmdb.org/t/p/w300/dR6JggIAt5E5PXcSfOHpGIFTEJQ.jpg',  1),
(197,'Rush',                           2013,'Ron Howard',                   'Drame',     'Sport',               'https://image.tmdb.org/t/p/w300/5k7Ggd6sqJQSGWCiHxICqkMhUSS.jpg',  1),
(198,'The Imitation Game',             2014,'Morten Tyldum',                'Drame',     'Biopic',              'https://image.tmdb.org/t/p/w300/noUp0XOqIcmgefRnRZa1nhtRvWO.jpg',  1),
(199,'Ex Machina',                     2014,'Alex Garland',                 'SF',        'Thriller',            'https://image.tmdb.org/t/p/w300/btdCB0EzFMQzDDm5SHpVSz5CInb.jpg',  1),
(200,'Annihilation',                   2018,'Alex Garland',                 'SF',        'Horreur',             'https://image.tmdb.org/t/p/w300/3M4Mhx0V2jOJI3bHb0siyMqIkLD.jpg',  1),
(201,'Looper',                         2012,'Rian Johnson',                 'SF',        'Action',              'https://image.tmdb.org/t/p/w300/xNSHD3wtTVpJOJLyl1RKfaHmkWE.jpg',  1),
(202,'Edge of Tomorrow',               2014,'Doug Liman',                   'SF',        'Action',              'https://image.tmdb.org/t/p/w300/7D2hOaKiMqEGalFjQ4oa1O75FgJ.jpg',  1),
(203,'Minority Report',                2002,'Steven Spielberg',             'SF',        'Thriller',            'https://image.tmdb.org/t/p/w300/7dkopLr78XaFHnPGnIjMXEhQ5xD.jpg',  1),
(204,'A.I. Intelligence artificielle', 2001,'Steven Spielberg',             'SF',        'Drame',               'https://image.tmdb.org/t/p/w300/n7GRmBB9z0S2VvS7ZcVpSEyymFi.jpg',  1),
(205,'Ready Player One',               2018,'Steven Spielberg',             'SF',        'Aventure',            'https://image.tmdb.org/t/p/w300/pU1UecCFmdMIhAlJEjXFtWq0Ck7.jpg',  1),
(206,'The Fabelmans',                  2022,'Steven Spielberg',             'Drame',     'Autobiographique',    'https://image.tmdb.org/t/p/w300/9r0BcRwFTVvdkFJVhcBJNhLrDNl.jpg',  1),
(207,'West Side Story',                2021,'Steven Spielberg',             'Comédie',   'Musical',             'https://image.tmdb.org/t/p/w300/dUz0k0HZcFchEkKLfBMYpGmDVW6.jpg',  1),
(208,'Babylon',                        2022,'Damien Chazelle',              'Drame',     'Historique',          'https://image.tmdb.org/t/p/w300/ym7hLLFmYbp5usYvKKPvPf30Cbj.jpg',  1),
(209,'The Northman',                   2022,'Robert Eggers',                'Action',    'Historique',          'https://image.tmdb.org/t/p/w300/ZsSPMkCMOwnIoD09vRWBzGUaHnJ.jpg',  1),
(210,'The Banshees of Inisherin',      2022,'Martin McDonagh',              'Drame',     'Comédie noire',       'https://image.tmdb.org/t/p/w300/kAmOdMPDeHRlNMqz7ORcHlnUviy.jpg',  1),
(211,'Aftersun',                       2022,'Charlotte Wells',              'Drame',     'Nostalgique',         'https://image.tmdb.org/t/p/w300/oMRaiCpdbVMGDBF78QFnEBxTWpM.jpg',  1),
(212,'Past Lives',                     2023,'Celine Song',                  'Drame',     'Romance',             'https://image.tmdb.org/t/p/w300/k3waqVXCHQpqmxMQlJOGAR3BXQY.jpg',  1),
(213,'The Whale',                      2022,'Darren Aronofsky',             'Drame',     'Psychologique',       'https://image.tmdb.org/t/p/w300/jQ0gylJMxWSL490sy0RrPj1Lj7e.jpg',  1),
(214,'Tár',                            2022,'Todd Field',                   'Drame',     'Musique',             'https://image.tmdb.org/t/p/w300/y348HCMdkHXVQiqflj0hJ1gajJh.jpg',  1),
(215,'Decision to Leave',              2022,'Park Chan-wook',               'Thriller',  'Romance',             'https://image.tmdb.org/t/p/w300/3B1WgAkpbUCfMk9KN7XqrSnhVER.jpg',  1),
(216,'Memories of Murder',             2003,'Bong Joon-ho',                 'Policier',  'Drame',               'https://image.tmdb.org/t/p/w300/lMKnCRU3fhSRkbvVHE3bPZv3Kdp.jpg',  1),
(217,'Burning',                        2018,'Lee Chang-dong',               'Drame',     'Thriller',            'https://image.tmdb.org/t/p/w300/jWVZXJmTJM7JFtbKtlJJTNpKCx0.jpg',  1),
(218,'Snowpiercer',                    2013,'Bong Joon-ho',                 'SF',        'Action',              'https://image.tmdb.org/t/p/w300/cUfGqafAVQkatQ7N4y08RNV3vtt.jpg',  1),
(219,'Jurassic Park',                  1993,'Steven Spielberg',             'SF',        'Aventure',            'https://image.tmdb.org/t/p/w300/oU7Oq2kFAAlGqbU4VoAE36g4hoI.jpg',  1),
(220,'Shutter Island',                 2010,'Martin Scorsese',              'Thriller',  'Psychologique',       'https://image.tmdb.org/t/p/w300/dolotEBBn8OTBASEevMR7QPQzFO.jpg',  1),
(221,'Drive',                          2011,'Nicolas Winding Refn',         'Crime',     'Drame',               'https://image.tmdb.org/t/p/w300/602vevIURmpzkiZubgk0We7OYHL.jpg',  1),
(222,'La Chasse',                      2012,'Thomas Vinterberg',            'Drame',     'Social',              'https://image.tmdb.org/t/p/w300/lmdaJZNRvpyY7GGUuZZEEVV1Bk6.jpg',  1),
(223,'Warrior',                        2011,'Gavin O''Connor',              'Drame',     'Sport',               'https://image.tmdb.org/t/p/w300/6WkqBPRYCiOaqOMHZnvMhNXb8vU.jpg',  1),
(224,'Joker',                          2019,'Todd Phillips',                'Drame',     'Super-héros',         'https://image.tmdb.org/t/p/w300/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',  1),
(225,'Logan',                          2017,'James Mangold',                'Action',    'Super-héros',         'https://image.tmdb.org/t/p/w300/45Y1G5FEgttPNGmHOmEGXJiWFKj.jpg',  1),
(226,'Blue Velvet',                    1986,'David Lynch',                  'Thriller',  'Mystère',             'https://image.tmdb.org/t/p/w300/vFzfJHEBBsPaJkgz0f5kX9PiHp9.jpg',  1)
on conflict (id) do nothing;

-- Réinitialiser la séquence
select setval('public.films_id_seq', (select max(id) from public.films) + 1);
