export const BALANCE = {
  TAILLE_EQUIPE: 6,
  TAILLE_EQUIPE_MIN: 5,
  MODE_EQUIPE: 'choix' as 'aleatoire' | 'recents' | 'choix',
  DIFFICULTE: 1.0,
  LEVEL: 50,
  CRIT_BASE: 6.25,
  CRIT_MULT: 1.5,
  RANDOM_RANGE: [0.85, 1.0] as [number, number],

  SUPER_EFFECTIVE_MULT: 2.0,
  NOT_EFFECTIVE_MULT: 0.3,
  DAMAGE_CAP_PCT: 0.40,

  CLIPPY_PV_BASE: 550,
  CLIPPY_ATK: 90,
  CLIPPY_DEF: 85,
  CLIPPY_SPE: 80,
  CLIPPY_VIT: 75,
  CLIPPY_HEALS: 2,
  CLIPPY_HEAL_THRESHOLDS: [0.66, 0.33] as [number, number],
  CLIPPY_HEAL_AMOUNT: 0.22,
  CLIPPY_ADAPT_INTERVAL: 3,
  CLIPPY_RANDOM_CHANCE: 0.20,
  CLIPPY_POKEBALL_THRESHOLD: 0.15,

  STAT_SCALING: {
    pvBase: 80,
    pvRange: 50,
    atkBase: 70,
    atkRange: 40,
    defBase: 65,
    defRange: 35,
    speBase: 65,
    speRange: 35,
    vitBase: 60,
    vitRange: 40,
  },
  YEAR_DEF_FACTOR: 0.4,
  YEAR_REF: 2025,
  RATING_ATK_BONUS: 2,
} as const
