import type { Move, FilmType } from '../types'

export const MOVES_BY_TYPE: Record<FilmType, Move[]> = {
  // ═══ ACTION (Action + Guerre) ═══════════════════════
  action: [
    { id: 'cascade_explosive', nom: 'Cascade Explosive', type: 'action', categorie: 'physique',
      puissance: 90, precision: 85, pp: 10, effet: { recoil: 0.2 },
      texte: '{film} déclenche une Cascade Explosive !' },
    { id: 'tir_rafale', nom: 'Tir en Rafale', type: 'action', categorie: 'physique',
      puissance: 25, precision: 100, pp: 15, effet: { multiHits: [2, 5] },
      texte: '{film} ouvre le feu en rafale !' },
    { id: 'course_poursuite', nom: 'Course-Poursuite', type: 'action', categorie: 'physique',
      puissance: 40, precision: 100, pp: 20, priorite: 1,
      texte: '{film} contre-attaque en premier !' },
    { id: 'bullet_time_action', nom: 'Bullet Time', type: 'action', categorie: 'statut',
      puissance: 0, precision: 100, pp: 10,
      effet: { statMods: [{ stat: 'vit', stages: 2, target: 'self' }, { stat: 'esquive', stages: 1, target: 'self' }] },
      texte: '{film} ralentit le temps !' },
    { id: 'explosion_finale', nom: 'Explosion Finale', type: 'action', categorie: 'speciale',
      puissance: 130, precision: 90, pp: 5,
      effet: { statMods: [{ stat: 'spe', stages: -2, target: 'self' }] },
      texte: '{film} déchaîne une Explosion Finale !' },
    { id: 'tir_artillerie', nom: "Tir d'Artillerie", type: 'action', categorie: 'physique',
      puissance: 120, precision: 70, pp: 5,
      texte: "{film} tire à l'artillerie lourde !" },
    { id: 'charge_heroique', nom: 'Charge Héroïque', type: 'action', categorie: 'physique',
      puissance: 100, precision: 90, pp: 5, effet: { recoil: 0.33 },
      texte: '{film} lance une Charge Héroïque !' },
    { id: 'tranchee', nom: 'Tranchée', type: 'action', categorie: 'statut',
      puissance: 0, precision: 100, pp: 10,
      effet: { statMods: [{ stat: 'def', stages: 2, target: 'self' }] },
      texte: '{film} se met à couvert dans la Tranchée !' },
    { id: 'pilonnage', nom: 'Pilonnage', type: 'action', categorie: 'speciale',
      puissance: 25, precision: 90, pp: 15, effet: { multiHits: [2, 5] },
      texte: '{film} pilonne sans relâche !' },
    { id: 'sacrifice_guerre', nom: 'Sacrifice', type: 'action', categorie: 'physique',
      puissance: 200, precision: 100, pp: 1, effet: { selfKO: true },
      texte: '{film} se sacrifie dans un ultime assaut !' },
  ],

  // ═══ AVENTURE (Aventure + Western) ═════════════════
  aventure: [
    { id: 'appel_aventure', nom: "Appel de l'Aventure", type: 'aventure', categorie: 'statut',
      puissance: 0, precision: 100, pp: 15,
      effet: { statMods: [{ stat: 'atk', stages: 1, target: 'self' }, { stat: 'vit', stages: 1, target: 'self' }] },
      texte: "{film} répond à l'Appel de l'Aventure !" },
    { id: 'carte_tresor', nom: 'Carte au Trésor', type: 'aventure', categorie: 'statut',
      puissance: 0, precision: 100, pp: 10, critBonus: 99,
      effet: { statMods: [{ stat: 'atk', stages: 1, target: 'self' }] },
      texte: '{film} consulte la Carte au Trésor !' },
    { id: 'saut_foi', nom: 'Saut de la Foi', type: 'aventure', categorie: 'physique',
      puissance: 140, precision: 60, pp: 5,
      texte: '{film} tente un Saut de la Foi !' },
    { id: 'compagnon_fidele', nom: 'Compagnon Fidèle', type: 'aventure', categorie: 'statut',
      puissance: 0, precision: 100, pp: 5,
      effet: { heal: 0.25, statMods: [{ stat: 'def', stages: 1, target: 'self' }] },
      texte: '{film} invoque son Compagnon Fidèle !' },
    { id: 'duel_soleil', nom: 'Duel au Soleil', type: 'aventure', categorie: 'physique',
      puissance: 80, precision: 95, pp: 10, priorite: 1, critBonus: 3,
      texte: '{film} provoque un Duel au Soleil !' },
    { id: 'tir_precis', nom: 'Tir Précis', type: 'aventure', categorie: 'speciale',
      puissance: 75, precision: 0, pp: 10, critBonus: 99,
      texte: '{film} ajuste un Tir Précis imparable !' },
    { id: 'nuage_poussiere', nom: 'Nuage de Poussière', type: 'aventure', categorie: 'statut',
      puissance: 0, precision: 100, pp: 15,
      effet: { statMods: [{ stat: 'precision', stages: -2, target: 'opponent' }] },
      texte: '{film} soulève un Nuage de Poussière !' },
    { id: 'hors_la_loi', nom: 'Hors-la-Loi', type: 'aventure', categorie: 'statut',
      puissance: 0, precision: 100, pp: 10,
      effet: { statMods: [{ stat: 'atk', stages: 2, target: 'self' }] },
      texte: '{film} passe Hors-la-Loi !' },
    { id: 'derniere_balle', nom: 'Dernière Balle', type: 'aventure', categorie: 'speciale',
      puissance: 100, precision: 90, pp: 5,
      texte: '{film} tire sa Dernière Balle !' },
  ],

  // ═══ HORREUR ═══════════════════════════════════════
  horreur: [
    { id: 'jump_scare', nom: 'Jump Scare', type: 'horreur', categorie: 'physique',
      puissance: 80, precision: 100, pp: 10, priorite: 1,
      effet: { flinchChance: 40 },
      texte: '{film} déclenche un Jump Scare !' },
    { id: 'presence_malefique', nom: 'Présence Maléfique', type: 'horreur', categorie: 'statut',
      puissance: 0, precision: 100, pp: 15,
      effet: { statMods: [{ stat: 'atk', stages: -2, target: 'opponent' }] },
      texte: '{film} invoque une Présence Maléfique…' },
    { id: 'cri_strident', nom: 'Cri Strident', type: 'horreur', categorie: 'speciale',
      puissance: 85, precision: 90, pp: 10,
      effet: { status: 'paralysie', statusChance: 25 },
      texte: '{film} pousse un Cri Strident !' },
    { id: 'found_footage', nom: 'Found Footage', type: 'horreur', categorie: 'statut',
      puissance: 0, precision: 100, pp: 15,
      effet: { statMods: [{ stat: 'precision', stages: -2, target: 'opponent' }] },
      texte: '{film} projette un Found Footage tremblant !' },
    { id: 'nuit_sans_fin', nom: 'Nuit sans Fin', type: 'horreur', categorie: 'statut',
      puissance: 0, precision: 100, pp: 5,
      effet: { statMods: [{ stat: 'spe', stages: 2, target: 'self' }, { stat: 'atk', stages: 1, target: 'self' }] },
      texte: '{film} installe la Nuit sans Fin…' },
  ],

  // ═══ COMÉDIE (Comédie + Musical) ═══════════════════
  comedie: [
    { id: 'tarte_creme', nom: 'Tarte à la Crème', type: 'comedie', categorie: 'physique',
      puissance: 50, precision: 100, pp: 20,
      effet: { flinchChance: 40 },
      texte: '{film} balance une Tarte à la Crème !' },
    { id: 'quiproquo', nom: 'Quiproquo', type: 'comedie', categorie: 'statut',
      puissance: 0, precision: 85, pp: 15,
      effet: { status: 'confusion', statusChance: 100 },
      texte: '{film} crée un Quiproquo monstre !' },
    { id: 'running_gag', nom: 'Running Gag', type: 'comedie', categorie: 'speciale',
      puissance: 70, precision: 100, pp: 15, critBonus: 2,
      texte: '{film} enchaîne le Running Gag !' },
    { id: 'punchline', nom: 'Punchline', type: 'comedie', categorie: 'speciale',
      puissance: 90, precision: 90, pp: 10, critBonus: 4,
      texte: '{film} lâche une Punchline fatale !' },
    { id: 'slapstick', nom: 'Slapstick', type: 'comedie', categorie: 'physique',
      puissance: 20, precision: 80, pp: 15, effet: { multiHits: [2, 5] },
      texte: '{film} enchaîne les gags Slapstick !' },
    { id: 'numero_claquettes', nom: 'Numéro de Claquettes', type: 'comedie', categorie: 'physique',
      puissance: 20, precision: 95, pp: 15, effet: { multiHits: [2, 5] },
      texte: '{film} exécute un Numéro de Claquettes !' },
    { id: 'note_aigue', nom: 'Note Aiguë', type: 'comedie', categorie: 'speciale',
      puissance: 80, precision: 90, pp: 10,
      effet: { status: 'paralysie', statusChance: 20 },
      texte: '{film} pousse une Note Aiguë !' },
    { id: 'refrain_entetant', nom: 'Refrain Entêtant', type: 'comedie', categorie: 'statut',
      puissance: 0, precision: 90, pp: 15,
      effet: { status: 'confusion', statusChance: 80, statMods: [{ stat: 'precision', stages: -1, target: 'opponent' }] },
      texte: '{film} lance un Refrain Entêtant !' },
    { id: 'choregraphie', nom: 'Chorégraphie', type: 'comedie', categorie: 'statut',
      puissance: 0, precision: 100, pp: 10,
      effet: { statMods: [{ stat: 'vit', stages: 1, target: 'self' }, { stat: 'esquive', stages: 1, target: 'self' }] },
      texte: '{film} exécute une Chorégraphie !' },
    { id: 'final_grandiose', nom: 'Final Grandiose', type: 'comedie', categorie: 'speciale',
      puissance: 100, precision: 85, pp: 5,
      texte: '{film} livre un Final Grandiose !' },
  ],

  // ═══ DRAME (Drame + Documentaire) ══════════════════
  drame: [
    { id: 'monologue_dechirant', nom: 'Monologue Déchirant', type: 'drame', categorie: 'statut',
      puissance: 0, precision: 100, pp: 15,
      effet: { statMods: [{ stat: 'atk', stages: -1, target: 'opponent' }, { stat: 'spe', stages: -1, target: 'opponent' }] },
      texte: '{film} livre un Monologue Déchirant…' },
    { id: 'larmes', nom: 'Larmes', type: 'drame', categorie: 'statut',
      puissance: 0, precision: 100, pp: 5,
      effet: { heal: 0.5 },
      texte: '{film} verse des Larmes…' },
    { id: 'revelation', nom: 'Révélation', type: 'drame', categorie: 'speciale',
      puissance: 140, precision: 70, pp: 5,
      texte: '{film} assène une Révélation !' },
    { id: 'silence_pesant', nom: 'Silence Pesant', type: 'drame', categorie: 'statut',
      puissance: 0, precision: 90, pp: 10,
      effet: { status: 'confusion', statusChance: 100 },
      texte: '{film} installe un Silence Pesant…' },
    { id: 'plan_sequence', nom: 'Plan Séquence', type: 'drame', categorie: 'speciale',
      puissance: 70, precision: 0, pp: 15,
      texte: '{film} enchaîne en Plan Séquence !' },
    { id: 'faits_accablants', nom: 'Faits Accablants', type: 'drame', categorie: 'speciale',
      puissance: 75, precision: 100, pp: 10,
      texte: '{film} expose des Faits Accablants !' },
    { id: 'voix_off', nom: 'Voix Off', type: 'drame', categorie: 'statut',
      puissance: 0, precision: 100, pp: 15,
      effet: { statMods: [{ stat: 'atk', stages: -1, target: 'opponent' }] },
      texte: '{film} impose sa Voix Off…' },
    { id: 'archives', nom: 'Archives', type: 'drame', categorie: 'statut',
      puissance: 0, precision: 100, pp: 10,
      effet: { statMods: [{ stat: 'spe', stages: 2, target: 'self' }] },
      texte: '{film} consulte les Archives !' },
    { id: 'revelation_choc', nom: 'Révélation Choc', type: 'drame', categorie: 'speciale',
      puissance: 80, precision: 95, pp: 10,
      effet: { flinchChance: 30 },
      texte: '{film} provoque une Révélation Choc !' },
    { id: 'plaidoyer', nom: 'Plaidoyer', type: 'drame', categorie: 'statut',
      puissance: 0, precision: 100, pp: 10,
      effet: { statMods: [{ stat: 'spe', stages: 2, target: 'self' }] },
      texte: '{film} prononce un Plaidoyer !' },
  ],

  // ═══ SCIENCE-FICTION ═══════════════════════════════
  sciencefiction: [
    { id: 'rayon_laser', nom: 'Rayon Laser', type: 'sciencefiction', categorie: 'speciale',
      puissance: 85, precision: 95, pp: 15,
      texte: '{film} tire un Rayon Laser !' },
    { id: 'paradoxe_temporel', nom: 'Paradoxe Temporel', type: 'sciencefiction', categorie: 'statut',
      puissance: 0, precision: 100, pp: 5,
      effet: { statMods: [{ stat: 'vit', stages: 3, target: 'self' }] },
      texte: '{film} déclenche un Paradoxe Temporel !' },
    { id: 'faille_spatiale', nom: 'Faille Spatiale', type: 'sciencefiction', categorie: 'speciale',
      puissance: 100, precision: 85, pp: 5,
      texte: '{film} ouvre une Faille Spatiale !' },
    { id: 'singularite', nom: 'Singularité', type: 'sciencefiction', categorie: 'speciale',
      puissance: 150, precision: 65, pp: 3,
      texte: '{film} crée une Singularité !' },
    { id: 'ia_hostile', nom: 'IA Hostile', type: 'sciencefiction', categorie: 'statut',
      puissance: 0, precision: 90, pp: 10,
      effet: { statMods: [{ stat: 'atk', stages: -1, target: 'opponent' }, { stat: 'atk', stages: 1, target: 'self' }] },
      texte: '{film} active l\'IA Hostile !' },
  ],

  // ═══ FANTASTIQUE ═══════════════════════════════════
  fantastique: [
    { id: 'sort_ancestral', nom: 'Sort Ancestral', type: 'fantastique', categorie: 'speciale',
      puissance: 80, precision: 90, pp: 10,
      effet: { status: 'poison', statusChance: 20 },
      texte: '{film} incante un Sort Ancestral !' },
    { id: 'bouclier_magique', nom: 'Bouclier Magique', type: 'fantastique', categorie: 'statut',
      puissance: 0, precision: 100, pp: 5,
      effet: { statMods: [{ stat: 'def', stages: 3, target: 'self' }, { stat: 'spe', stages: 1, target: 'self' }] },
      texte: '{film} dresse un Bouclier Magique !' },
    { id: 'invocation', nom: 'Invocation', type: 'fantastique', categorie: 'physique',
      puissance: 85, precision: 90, pp: 10,
      texte: '{film} réalise une Invocation !' },
    { id: 'malediction', nom: 'Malédiction', type: 'fantastique', categorie: 'statut',
      puissance: 0, precision: 90, pp: 10,
      effet: { status: 'poison', statusChance: 100, statMods: [{ stat: 'def', stages: -1, target: 'opponent' }] },
      texte: '{film} lance une Malédiction !' },
    { id: 'l_elu', nom: "L'Élu", type: 'fantastique', categorie: 'statut',
      puissance: 0, precision: 100, pp: 3,
      effet: { statMods: [
        { stat: 'atk', stages: 1, target: 'self' }, { stat: 'def', stages: 1, target: 'self' },
        { stat: 'spe', stages: 1, target: 'self' }, { stat: 'vit', stages: 1, target: 'self' },
      ] },
      texte: "{film} est L'Élu !" },
  ],

  // ═══ THRILLER (Thriller + Policier) ════════════════
  thriller: [
    { id: 'compte_rebours', nom: 'Compte à Rebours', type: 'thriller', categorie: 'statut',
      puissance: 0, precision: 100, pp: 5,
      effet: { status: 'poison', statusChance: 100, statMods: [{ stat: 'def', stages: -1, target: 'opponent' }] },
      texte: '{film} lance un Compte à Rebours…' },
    { id: 'filature', nom: 'Filature', type: 'thriller', categorie: 'physique',
      puissance: 90, precision: 90, pp: 10,
      texte: '{film} engage une Filature !' },
    { id: 'tension', nom: 'Tension', type: 'thriller', categorie: 'statut',
      puissance: 0, precision: 100, pp: 15,
      effet: { statMods: [{ stat: 'vit', stages: 1, target: 'self' }, { stat: 'esquive', stages: 1, target: 'self' }] },
      texte: '{film} fait monter la Tension !' },
    { id: 'coup_monte', nom: 'Coup Monté', type: 'thriller', categorie: 'statut',
      puissance: 0, precision: 100, pp: 10, critBonus: 99,
      effet: { statMods: [{ stat: 'atk', stages: 1, target: 'self' }] },
      texte: '{film} prépare un Coup Monté !' },
    { id: 'twist_final', nom: 'Twist Final', type: 'thriller', categorie: 'speciale',
      puissance: 95, precision: 80, pp: 10,
      texte: '{film} assène un Twist Final !' },
    { id: 'interrogatoire', nom: 'Interrogatoire', type: 'thriller', categorie: 'statut',
      puissance: 0, precision: 100, pp: 10,
      effet: { statMods: [{ stat: 'def', stages: -2, target: 'opponent' }] },
      texte: '{film} mène un Interrogatoire serré !' },
    { id: 'fusillade', nom: 'Fusillade', type: 'thriller', categorie: 'physique',
      puissance: 25, precision: 90, pp: 15, effet: { multiHits: [2, 5] },
      texte: '{film} ouvre une Fusillade !' },
    { id: 'braquage', nom: 'Braquage', type: 'thriller', categorie: 'statut',
      puissance: 0, precision: 90, pp: 10,
      effet: { statMods: [{ stat: 'atk', stages: -1, target: 'opponent' }, { stat: 'atk', stages: 1, target: 'self' }] },
      texte: '{film} réalise un Braquage !' },
    { id: 'indic', nom: 'Indic', type: 'thriller', categorie: 'statut',
      puissance: 0, precision: 100, pp: 5, critBonus: 99,
      effet: { statMods: [{ stat: 'precision', stages: 1, target: 'self' }] },
      texte: '{film} utilise son Indic !' },
    { id: 'course_bagnole', nom: 'Course-Poursuite en Bagnole', type: 'thriller', categorie: 'physique',
      puissance: 45, precision: 100, pp: 20, priorite: 1,
      texte: '{film} fonce en Course-Poursuite !' },
  ],

  // ═══ ANIMATION ═════════════════════════════════════
  animation: [
    { id: 'etincelle_magie', nom: 'Étincelle de Magie', type: 'animation', categorie: 'speciale',
      puissance: 80, precision: 100, pp: 15,
      texte: '{film} lance une Étincelle de Magie !' },
    { id: 'cartoon_physics', nom: 'Cartoon Physics', type: 'animation', categorie: 'physique',
      puissance: 140, precision: 60, pp: 5,
      texte: '{film} défie les lois de la physique !' },
    { id: 'chanson_entrainante', nom: 'Chanson Entraînante', type: 'animation', categorie: 'statut',
      puissance: 0, precision: 100, pp: 10,
      effet: { statMods: [{ stat: 'spe', stages: 1, target: 'self' }, { stat: 'atk', stages: 1, target: 'self' }] },
      texte: '{film} entonne une Chanson Entraînante !' },
    { id: 'sidekick_rigolo', nom: 'Sidekick Rigolo', type: 'animation', categorie: 'physique',
      puissance: 40, precision: 100, pp: 15, effet: { multiHits: [2, 2] },
      texte: '{film} envoie son Sidekick Rigolo !' },
    { id: 'morale_histoire', nom: "Morale de l'Histoire", type: 'animation', categorie: 'statut',
      puissance: 0, precision: 100, pp: 5,
      effet: { heal: 0.3, statMods: [{ stat: 'def', stages: 1, target: 'self' }] },
      texte: "{film} révèle la Morale de l'Histoire !" },
  ],

  // ═══ ROMANCE ═══════════════════════════════════════
  romance: [
    { id: 'coup_foudre', nom: 'Coup de Foudre', type: 'romance', categorie: 'statut',
      puissance: 0, precision: 100, pp: 10,
      effet: { statMods: [{ stat: 'atk', stages: -2, target: 'opponent' }] },
      texte: '{film} provoque un Coup de Foudre !' },
    { id: 'baiser_langoureux', nom: 'Baiser Langoureux', type: 'romance', categorie: 'statut',
      puissance: 0, precision: 75, pp: 10,
      effet: { status: 'sommeil', statusChance: 100 },
      texte: '{film} envoie un Baiser Langoureux…' },
    { id: 'lettre_amour', nom: "Lettre d'Amour", type: 'romance', categorie: 'speciale',
      puissance: 70, precision: 0, pp: 15,
      texte: "{film} envoie une Lettre d'Amour !" },
    { id: 'triangle_amoureux', nom: 'Triangle Amoureux', type: 'romance', categorie: 'statut',
      puissance: 0, precision: 85, pp: 15,
      effet: { status: 'confusion', statusChance: 100 },
      texte: '{film} crée un Triangle Amoureux !' },
    { id: 'adieu_quai', nom: 'Adieu sur le Quai', type: 'romance', categorie: 'speciale',
      puissance: 65, precision: 100, pp: 10,
      effet: { statMods: [{ stat: 'vit', stages: -1, target: 'opponent' }, { stat: 'atk', stages: -1, target: 'opponent' }] },
      texte: '{film} joue un Adieu sur le Quai…' },
  ],
}
