import type { Move } from '../types'

interface SignatureEntry {
  patterns: string[]
  move: Move
}

export const SIGNATURES: SignatureEntry[] = [
  { patterns: ['fight club'],
    move: { id: 'sig_dedoublement', nom: 'Dédoublement', type: 'action', categorie: 'physique',
      puissance: 45, precision: 100, pp: 10, effet: { multiHits: [2, 2], recoil: 0.1 },
      texte: '{film} invoque Tyler Durden et frappe deux fois !' } },
  { patterns: ['wall-e', 'wall·e'],
    move: { id: 'sig_compacteur', nom: 'Compacteur de Déchets', type: 'animation', categorie: 'physique',
      puissance: 80, precision: 100, pp: 10,
      effet: { statMods: [{ stat: 'vit', stages: -1, target: 'opponent' }] },
      texte: '{film} écrase un cube de détritus !' } },
  { patterns: ['pulp fiction'],
    move: { id: 'sig_recit_nonlineaire', nom: 'Récit Non-Linéaire', type: 'thriller', categorie: 'speciale',
      puissance: 85, precision: 90, pp: 10, critBonus: 3,
      texte: '{film} brouille la chronologie !' } },
  { patterns: ['matrix', 'the matrix'],
    move: { id: 'sig_bullet_time', nom: 'Bullet Time', type: 'sciencefiction', categorie: 'statut',
      puissance: 0, precision: 100, pp: 5,
      effet: { statMods: [{ stat: 'esquive', stages: 3, target: 'self' }, { stat: 'vit', stages: 2, target: 'self' }] },
      texte: '{film} active le Bullet Time !' } },
  { patterns: ['shining', 'the shining'],
    move: { id: 'sig_me_voila', nom: '« Me voilà ! »', type: 'horreur', categorie: 'physique',
      puissance: 120, precision: 85, pp: 5, effet: { flinchChance: 50 },
      texte: 'ME VOILÀ ! {film} défonce la porte !' } },
  { patterns: ['seigneur des anneaux', 'lord of the rings'],
    move: { id: 'sig_anneau_unique', nom: "L'Anneau Unique", type: 'fantastique', categorie: 'statut',
      puissance: 0, precision: 100, pp: 3,
      effet: { statMods: [{ stat: 'esquive', stages: 2, target: 'self' }, { stat: 'atk', stages: 1, target: 'self' }] },
      texte: '{film} invoque le pouvoir de l\'Anneau Unique !' } },
  { patterns: ['alien'],
    move: { id: 'sig_chestburster', nom: 'Chestburster', type: 'horreur', categorie: 'speciale',
      puissance: 150, precision: 75, pp: 3,
      texte: '{film} libère un Chestburster !' } },
  { patterns: ['jurassic park'],
    move: { id: 'sig_breche_trex', nom: 'Brèche du T-Rex', type: 'aventure', categorie: 'physique',
      puissance: 100, precision: 90, pp: 5,
      effet: { flinchChance: 30, statMods: [{ stat: 'atk', stages: -1, target: 'opponent' }] },
      texte: '{film} déchaîne la Brèche du T-Rex !' } },
  { patterns: ['retour vers le futur', 'back to the future'],
    move: { id: 'sig_88mph', nom: '88 mph', type: 'sciencefiction', categorie: 'statut',
      puissance: 0, precision: 100, pp: 3,
      effet: { statMods: [{ stat: 'vit', stages: 3, target: 'self' }], heal: 0.25 },
      texte: '88 miles à l\'heure ! {film} remonte le temps !' } },
  { patterns: ['parrain', 'godfather'],
    move: { id: 'sig_offre', nom: 'Offre qu\'on ne peut Refuser', type: 'drame', categorie: 'statut',
      puissance: 0, precision: 100, pp: 5,
      effet: { flinchChance: 100, statMods: [{ stat: 'atk', stages: -1, target: 'opponent' }] },
      texte: '{film} fait une offre qu\'on ne peut pas refuser…' } },
  { patterns: ['psychose', 'psycho'],
    move: { id: 'sig_douche', nom: 'Scène de la Douche', type: 'horreur', categorie: 'physique',
      puissance: 30, precision: 95, pp: 10, effet: { multiHits: [2, 5] },
      texte: '{film} rejoue la Scène de la Douche !' } },
  { patterns: ['2001', 'odyssée de l\'espace', 'odyssee de l\'espace', 'space odyssey'],
    move: { id: 'sig_sorry_dave', nom: "I'm sorry, Dave", type: 'sciencefiction', categorie: 'statut',
      puissance: 0, precision: 100, pp: 5,
      effet: { statMods: [{ stat: 'precision', stages: -2, target: 'opponent' }, { stat: 'spe', stages: -1, target: 'opponent' }] },
      texte: '« I\'m sorry, Dave. » {film} verrouille les systèmes.' } },
  { patterns: ['blade runner'],
    move: { id: 'sig_voightkampff', nom: 'Test Voight-Kampff', type: 'sciencefiction', categorie: 'speciale',
      puissance: 90, precision: 100, pp: 5,
      effet: { clearStages: 'opponent' },
      texte: '{film} administre le Test Voight-Kampff !' } },
  { patterns: ['inception'],
    move: { id: 'sig_reve_dans_reve', nom: 'Rêve dans le Rêve', type: 'sciencefiction', categorie: 'speciale',
      puissance: 70, precision: 95, pp: 10,
      effet: { statMods: [{ stat: 'spe', stages: 1, target: 'self' }], status: 'confusion', statusChance: 30 },
      texte: '{film} plonge dans un Rêve dans le Rêve !' } },
  { patterns: ['parasite'],
    move: { id: 'sig_infiltration', nom: 'Infiltration', type: 'thriller', categorie: 'statut',
      puissance: 0, precision: 100, pp: 5,
      effet: { statMods: [{ stat: 'atk', stages: -1, target: 'opponent' }, { stat: 'def', stages: -1, target: 'opponent' },
        { stat: 'atk', stages: 1, target: 'self' }] },
      texte: '{film} s\'infiltre en douceur…' } },
  { patterns: ['chihiro', 'spirited away'],
    move: { id: 'sig_banquet_maudit', nom: 'Banquet Maudit', type: 'animation', categorie: 'statut',
      puissance: 0, precision: 100, pp: 5,
      effet: { statMods: [{ stat: 'atk', stages: -1, target: 'opponent' }, { stat: 'def', stages: -1, target: 'opponent' }] },
      texte: '{film} transforme l\'adversaire au Banquet Maudit !' } },
  { patterns: ['akira'],
    move: { id: 'sig_mutation_tetsuo', nom: 'Mutation de Tetsuo', type: 'sciencefiction', categorie: 'statut',
      puissance: 0, precision: 100, pp: 5,
      effet: { statMods: [{ stat: 'atk', stages: 2, target: 'self' }], recoil: 0.15 },
      texte: 'TETSUO ! {film} mute de façon incontrôlable !' } },
  { patterns: ['kill bill'],
    move: { id: 'sig_five_point_palm', nom: 'Five Point Palm', type: 'action', categorie: 'physique',
      puissance: 200, precision: 50, pp: 3,
      texte: '{film} exécute la technique des Cinq Points !' } },
  { patterns: ['mad max', 'fury road'],
    move: { id: 'sig_war_rig', nom: 'War Rig', type: 'action', categorie: 'physique',
      puissance: 100, precision: 90, pp: 5, priorite: 1, effet: { recoil: 0.25 },
      texte: '{film} fonce avec le War Rig !' } },
  { patterns: ['silence des agneaux', 'silence of the lambs'],
    move: { id: 'sig_diner_hannibal', nom: 'Dîner avec Hannibal', type: 'thriller', categorie: 'statut',
      puissance: 0, precision: 100, pp: 5,
      effet: { statMods: [{ stat: 'spe', stages: -2, target: 'opponent' }] },
      texte: '{film} invite l\'adversaire à dîner avec Hannibal…' } },
  { patterns: ['memento'],
    move: { id: 'sig_memoire_courte', nom: 'Mémoire Courte', type: 'thriller', categorie: 'statut',
      puissance: 0, precision: 100, pp: 5,
      effet: { clearStages: 'opponent' },
      texte: '{film} efface la mémoire ! Stats adverses réinitialisées !' } },
  { patterns: ['grand bleu', 'big blue'],
    move: { id: 'sig_apnee', nom: 'Apnée', type: 'drame', categorie: 'speciale',
      puissance: 100, precision: 90, pp: 5,
      effet: { statMods: [{ stat: 'esquive', stages: 1, target: 'self' }] },
      texte: '{film} plonge en Apnée !' } },
  { patterns: ['scarface'],
    move: { id: 'sig_say_hello', nom: 'Say Hello to my Little Friend', type: 'action', categorie: 'physique',
      puissance: 40, precision: 70, pp: 5, effet: { multiHits: [2, 5] },
      texte: '« Say hello to my little friend ! » {film} arrose !' } },
  { patterns: ['reservoir dogs'],
    move: { id: 'sig_mexican_standoff', nom: 'Mexican Standoff', type: 'thriller', categorie: 'physique',
      puissance: 120, precision: 90, pp: 5, effet: { recoil: 0.33 },
      texte: '{film} déclenche un Mexican Standoff !' } },
  { patterns: ['donnie darko'],
    move: { id: 'sig_frank_lapin', nom: 'Frank le Lapin', type: 'fantastique', categorie: 'statut',
      puissance: 0, precision: 100, pp: 5,
      effet: { status: 'poison', statusChance: 100, statMods: [{ stat: 'def', stages: -1, target: 'opponent' }] },
      texte: '{film} invoque Frank le Lapin… Le compte à rebours commence.' } },
  { patterns: ['old boy', 'oldboy'],
    move: { id: 'sig_couloir_marteau', nom: 'Couloir au Marteau', type: 'action', categorie: 'physique',
      puissance: 30, precision: 0, pp: 10, effet: { multiHits: [3, 5] },
      texte: '{film} fonce dans le Couloir au Marteau !' } },
  { patterns: ['joker'],
    move: { id: 'sig_descente_enfers', nom: 'Descente aux Enfers', type: 'drame', categorie: 'speciale',
      puissance: 110, precision: 90, pp: 5,
      texte: '{film} entame une Descente aux Enfers !' } },
  { patterns: ['princesse mononoké', 'princess mononoke', 'mononoke'],
    move: { id: 'sig_colere_foret', nom: 'Colère de la Forêt', type: 'fantastique', categorie: 'speciale',
      puissance: 90, precision: 95, pp: 5,
      effet: { status: 'poison', statusChance: 30 },
      texte: '{film} déchaîne la Colère de la Forêt !' } },
  { patterns: ['whiplash'],
    move: { id: 'sig_not_my_tempo', nom: 'Not my Tempo', type: 'drame', categorie: 'statut',
      puissance: 0, precision: 100, pp: 10,
      effet: { statMods: [{ stat: 'precision', stages: -1, target: 'opponent' }], status: 'confusion', statusChance: 40 },
      texte: '« Not my tempo ! » {film} frappe la table !' } },
  { patterns: ['big lebowski', 'lebowski'],
    move: { id: 'sig_dude_abides', nom: 'The Dude Abides', type: 'comedie', categorie: 'statut',
      puissance: 0, precision: 100, pp: 5,
      effet: { heal: 0.25, statMods: [{ stat: 'esquive', stages: 1, target: 'self' }] },
      texte: '« The Dude abides. » {film} prend les choses cool.' } },
]

export function findSignature(titre: string): Move | null {
  const lower = titre.toLowerCase()
  for (const entry of SIGNATURES) {
    if (entry.patterns.some(p => lower.includes(p))) {
      return entry.move
    }
  }
  return null
}
