import type { ThemeDef, WeekInfo } from './types'

const pad2 = (n: number) => String(n).padStart(2, '0')

export const neutreTheme: ThemeDef = {
  key: 'neutre',
  label: 'Neutre',

  nav: {
    home: 'Accueil',
    videoclub: 'Vidéoclub',
    catEvenement: 'Évènement collectif',
    semaine: 'Films de la semaine',
    duels: 'Duels',
    catFilms: 'Films',
    films: 'Liste de films',
    notes: 'Classements films',
    pires: 'Pires films',
    rattrapage: 'Rattrapages cinéma',
    watchlist: 'Mes watchlists',
    watchlistPublic: 'Watchlists publiques',
    catSocial: 'Social',
    forum: 'Forum',
    marathoniens: 'Marathoniens',
    classement: 'Classement joueurs',
    messages: 'Messages',
    catSecret: 'Secret',
    tamagotchi: 'Mon Alien',
    clippyRevanche: 'La revanche de Clippy',
    easterEggs: 'Easter eggs',
    profil: 'Mon profil',
    admin: 'Administration',
    logout: 'Déconnexion',
    login: 'Se connecter',
  },

  navCourt: {
    home: 'Accueil',
    films: 'Films',
    notes: 'Notes',
    forum: 'Forum',
    marathoniens: 'Joueurs',
  },

  vocab: {
    markSeen: 'Marquer comme vu',
    markSeenDone: 'Vu',
    unmarkSeen: 'Retirer des vus',
    notSeen: 'Jamais vu',
    addToList: 'Ajouter à une watchlist',
    level: 'Niveau',
    badge: 'Badge',
    badges: 'Badges',
    rating: 'Note',
    vote: 'Voter',
    weekFilm: 'Film de la semaine',
    duelScreening: 'Séance du duel',
    bonus48: 'Bonus 48 h',
    players: 'Les marathoniens',
    playerCount: 'marathoniens',
    playerCountUn: 'marathonien',
    player: 'Marathonien',
    week: 'Semaine',
    duel: 'Duel',
    forumTopic: 'Sujet',
    notesBest: 'Meilleurs films',
    rattrapage1: 'Débutant',
    rattrapage2: 'Intermédiaire',
    rattrapage3: 'Confirmé',
    eggFound: 'Découvert',
    eggsIntro: 'Des secrets sont cachés dans le site. Trouve-les tous pour les débloquer. Certains nécessitent du courage.',
    authTitle: 'Connexion',
    resetTitle: 'Nouveau mot de passe',
    empty: 'Aucun résultat.',
    loading: 'Chargement…',
    errorGeneric: 'Une erreur est survenue.',
    notFoundTitle: 'Page introuvable',
    notFoundText: 'Cette page n’existe pas.',
    searchFilms: 'Rechercher un titre, un réalisateur…',
    saved: 'Enregistré.',
    profileEmpty: 'Aucun film vu pour l’instant.',
    goodbye: 'À bientôt.',
    welcomeTitle: 'Bienvenue dans le Marathon',
    joinTitle: 'Rejoindre le Marathon en cours',
    joinPendingTitle: 'Demande en attente de validation',
    joinAcceptedTitle: 'Inscription acceptée — Saison {n}',
    toastSeenTitle: 'Vu — {titre}',
  },

  repliques: {},
  citations: [],
  expUnit: 'EXP',
  levels: null,

  levelLabel: (level: number) => `Niveau ${level}`,

  weekLabel: (w: WeekInfo) =>
    `SEMAINE ${w.semaine} / ${w.total} · SAISON ${pad2(w.saison)}`,

  weekCourt: (w: WeekInfo) => `${pad2(w.semaine)} / ${pad2(w.total)}`,

  eggs: [],
  radioTrack: null,
}
